"""Example 06: Put the generated CDL channel inside a tiny data link.

WHERE ARE WE IN THE COMMUNICATION SYSTEM?
-----------------------------------------

uncoded QPSK -> frequency-domain OFDM subcarriers
    -> [CDL MIMO channel application]
    -> perfect-CSI pseudo-inverse equalizer -> hard bits

This is the only current example that includes a transmitter-side data symbol,
the channel, and a receiver-side operation.

QUESTION
--------

How does H[k] distort QPSK data on each subcarrier, and how can an ideal
receiver undo a known MIMO channel?

INPUT -> OUTPUT
---------------

64 channel realizations + 2 Tx + 4 Rx + 64 subcarriers + QPSK + noise
    -> transmitted, received, and equalized constellations + BER

THE MAIN IDEALIZATION: PERFECT CSI
---------------------------------

The equalizer is given the exact H[k] generated by the simulator. A real
receiver must transmit pilots/DMRS, estimate H_hat[k], and use an imperfect
estimate. This example does not perform channel estimation.

ALSO NOT MODELED
----------------

No IFFT, cyclic prefix, timing/frequency synchronization, resource grid,
precoding, coding/LDPC, soft demapping, HARQ, or BLER Monte Carlo campaign.
This is a frequency-domain teaching model, not a complete 5G NR OFDM link.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from sionna_tutorial import AntennaArray, CDLChannel, get_backend
from sionna_tutorial.ofdm import run_perfect_csi_ofdm_demo
from sionna_tutorial.plotting import plot_constellations, save_or_show


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--backend", choices=["numpy", "cupy", "auto"], default="auto")
    parser.add_argument("--snr-db", type=float, default=20.0)
    parser.add_argument("--output", type=Path, default=Path("artifacts/06_ofdm_demo.png"))
    args = parser.parse_args()

    carrier = 3.5e9
    backend = get_backend(args.backend)
    channel = CDLChannel(
        "C",
        100e-9,
        carrier,
        tx_array=AntennaArray.ula(2, carrier),
        rx_array=AntennaArray.ula(4, carrier),
    )
    realization = channel.generate(64, seed=13, backend=backend)
    result = run_perfect_csi_ofdm_demo(
        realization,
        backend=backend,
        num_subcarriers=64,
        snr_db=args.snr_db,
        seed=14,
    )

    tx = backend.to_numpy(result.transmitted_symbols)
    rx = backend.to_numpy(result.received_symbols[:, 0])
    equalized = backend.to_numpy(result.equalized_symbols)
    fig = plot_constellations(tx, rx, equalized)
    fig.suptitle(
        f"CDL-C 2x4 frequency-domain demo | {backend.name} | "
        f"SNR={args.snr_db:g} dB | BER={result.bit_error_rate:.3e}",
        y=1.03,
    )
    save_or_show(fig, args.output)
    print(f"BER: {result.bit_error_rate:.6e}")


if __name__ == "__main__":
    main()
